name: Swift

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test-macos:
        runs-on: macos-13
        env:
            DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: swift build -v
            - name: Test
              run: swift test -v --enable-code-coverage
            - name: Coverage
              uses: Nef10/spm-lcov-action@macOS12Runner
              with:
                  output-file: ./coverage/lcov.info
            - name: Report Coverage
              uses: romeovs/lcov-reporter-action@v0.2.16
              with:
                  lcov-file: ./coverage/lcov.info
    test-linux:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                swift: [5.9]
        container: swift:${{ matrix.swift }}
        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: swift build
            - name: Run tests
              run: swift test
